language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'chart-line' ]; then cd .. && eval "mv $currentfolder chart-line" && cd chart-line; fi
after_script:
  - npm run coveralls

